name: CI
on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        poetry-version: [1.2.2]
        os: [ubuntu-20.04, macos-latest]
        include:
          - os: ubuntu-20.04
            path: ~/.cache/pip
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
    runs-on: ${{ matrix.os }}
    env:
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install tox tox-gh-actions
      - name: Cache Primes
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ matrix.python-version }}-${{ matrix.os }}-tox
      - name: Test with tox
        run: tox
